### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [THV/DocketMaster#1]
Hi:
What would be the license for this fine code?
Thanks!

**Comment by THV** [comment]
Hi, Philippe: Thank you for asking. Truthfully, I had not decided.  I was leaning on GPLv2+ and possibly considering Apache.  You know, it's much easier to advise others of these questions than to decide one's self.  Any recommendations from your own experience?

**Comment by THV** [comment]
I ended up going with GPL-2.0 and updated the project files accordingly.
